<template>
    <div>
        <TheHeader/>
        <main>
            <HeroSection/>
            <FeatureSection/>
            <DesignSection/>
            <ShowNow/>
            <BenefitSection/>
        </main>
        <FooterSection/>
    </div>
</template>
